name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --build-arg ROOT_DIR=/srv/jupyterhub -t username/my-jupyterhub:latest .

      - name: Test Docker Image
        run: |
          echo "Testing Docker image..."
          docker run --rm username/my-jupyterhub:latest echo "tested"

      - name: Push Docker Image
        run: |
          docker push username/my-jupyterhub:latest
